import { Product, Coupon, Review } from '@/types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'lumina-001',
    name: 'Lumina Botanical Hydrating Cleanser',
    brand: 'Lumina Botanicals',
    price: 38,
    originalPrice: 46,
    rating: 4.9,
    reviewCount: 128,
    stock: 45,
    category: 'cleanser',
    skinType: ['dry', 'sensitive', 'normal', 'combination'],
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1608248597262-838d14f70d0a?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=1000'
    ],
    description: 'A gentle, pH-balanced gel cleanser infused with soothing Chamomile, Rosehip Seed Extract, and Hyaluronic Acid to lift impurities without stripping skin barrier moisture.',
    ingredients: ['Water/Aqua', 'Glycerin', 'Rosa Canina (Rosehip) Seed Oil', 'Chamommila Recutita Flower Extract', 'Sodium Hyaluronate', 'Aloe Barbadensis Leaf Juice', 'Coco-Glucoside'],
    benefits: ['Maintains natural skin moisture barrier', 'Soothes inflammation and redness', 'Rinses clean with no tight residue'],
    usage: 'both',
    volume: '150ml / 5.1 fl. oz.',
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-01-15T00:00:00.000Z',
    updatedAt: '2026-01-15T00:00:00.000Z',
  },
  {
    id: 'lumina-002',
    name: 'Cellular Radiance Vitamin C + E Serum',
    brand: 'Lumina Lab',
    price: 72,
    originalPrice: 85,
    rating: 4.95,
    reviewCount: 240,
    stock: 18,
    category: 'serum',
    skinType: ['all', 'dry', 'oily', 'combination'],
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1608248597262-838d14f70d0a?auto=format&fit=crop&q=80&w=1000'
    ],
    description: 'Potent 15% L-Ascorbic Acid antioxidant serum stabilized with Tocopherol (Vitamin E) and Ferulic Acid. Brightens dark spots and protects against environmental photo-aging.',
    ingredients: ['Water/Aqua', 'L-Ascorbic Acid (15%)', 'Ethoxydiglycol', 'Tocopherol', 'Ferulic Acid', 'Sodium Hyaluronate', 'Panthenol'],
    benefits: ['Fades dark spots & hyperpigmentation', 'Boosts natural collagen synthesis', 'Protects against UV photo-damage'],
    usage: 'morning',
    volume: '30ml / 1.0 fl. oz.',
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-01-10T00:00:00.000Z',
    updatedAt: '2026-01-10T00:00:00.000Z',
  },
  {
    id: 'lumina-003',
    name: 'Aura Barrier Repair Ceramide Cream',
    brand: 'Aura Skincare',
    price: 58,
    originalPrice: 65,
    rating: 4.8,
    reviewCount: 94,
    stock: 32,
    category: 'moisturizer',
    skinType: ['dry', 'sensitive', 'normal'],
    images: [
      'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=1000'
    ],
    description: 'Rich velvet moisture cream formulated with 5 essential ceramides, cholesterol, and fatty acids to restore compromised skin barriers and prevent trans-epidermal water loss.',
    ingredients: ['Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Cholesterol', 'Phytosphingosine', 'Shea Butter', 'Squalane', 'Centella Asiatica'],
    benefits: ['Intensive 48-hour moisture barrier repair', 'Relieves skin itching and dry flaking', 'Non-comedogenic comforting finish'],
    usage: 'both',
    volume: '50ml / 1.7 fl. oz.',
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-02-01T00:00:00.000Z',
  },
  {
    id: 'lumina-004',
    name: 'Invisible Dew SPF 50 Mineral Sunscreen',
    brand: 'Lumina Sun',
    price: 42,
    originalPrice: 48,
    rating: 4.88,
    reviewCount: 165,
    stock: 60,
    category: 'sunscreen',
    skinType: ['all', 'sensitive', 'oily'],
    images: [
      'https://images.unsplash.com/photo-1567928269937-ae145459966c?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=1000'
    ],
    description: 'Ultra-lightweight 100% Zinc Oxide mineral sunscreen that blends effortlessly with zero white cast. Delivers broad spectrum UVA/UVB protection with a radiant dew drop glow.',
    ingredients: ['Zinc Oxide (18.5%)', 'Water/Aqua', 'Caprylic/Capric Triglyceride', 'Niacinamide', 'Green Tea Leaf Extract', 'Bisabolol'],
    benefits: ['Zero white-cast seamless blend', 'Reef-safe non-nano formula', 'Niacinamide oil control'],
    usage: 'morning',
    volume: '60ml / 2.0 fl. oz.',
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    createdAt: '2026-02-05T00:00:00.000Z',
    updatedAt: '2026-02-05T00:00:00.000Z',
  },
  {
    id: 'lumina-005',
    name: 'Retinol Youth Resurfacing Night Elixir',
    brand: 'Lumina Lab',
    price: 84,
    rating: 4.92,
    reviewCount: 88,
    stock: 14,
    category: 'serum',
    skinType: ['normal', 'combination', 'dry', 'oily'],
    images: [
      'https://images.unsplash.com/photo-1608248597262-838d14f70d0a?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=1000'
    ],
    description: 'Encapsulated 0.5% Pure Retinol combined with Bakuchiol and Peptide complexes to accelerate cellular turnover, soften fine lines, and refine enlarged pores overnight.',
    ingredients: ['Squalane', 'Encapsulated Retinol (0.5%)', 'Bakuchiol', 'Palmitoyl Tripeptide-1', 'Palmitoyl Tetrapeptide-7', 'Jojoba Oil'],
    benefits: ['Smooths fine lines & texture', 'Unclogs pores & clarifies skin', 'Encapsulated slow-release minimal irritation'],
    usage: 'evening',
    volume: '30ml / 1.0 fl. oz.',
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-01-20T00:00:00.000Z',
    updatedAt: '2026-01-20T00:00:00.000Z',
  },
  {
    id: 'lumina-006',
    name: 'Peptide Eye Recovery Serum Concentrate',
    brand: 'Aesop Luxe',
    price: 64,
    rating: 4.75,
    reviewCount: 52,
    stock: 25,
    category: 'eye-care',
    skinType: ['all'],
    images: [
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=1000'
    ],
    description: 'Cooling peptide serum targeting dark eye circles, under-eye puffiness, and crow’s feet wrinkles. Features a precision ceramic applicator tip.',
    ingredients: ['Water/Aqua', 'Caffeine (3%)', 'Acetyl Tetrapeptide-5', 'Eyeliss Peptide Complex', 'Hyaluronic Acid', 'Cucumber Extract'],
    benefits: ['Reduces dark circles & fatigue', 'Instantly depuffs under-eye bags', 'Smooths fine wrinkles'],
    usage: 'both',
    volume: '15ml / 0.5 fl. oz.',
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    createdAt: '2026-02-10T00:00:00.000Z',
    updatedAt: '2026-02-10T00:00:00.000Z',
  },
  {
    id: 'lumina-007',
    name: 'Clarifying BHA 2% Salicylic Acid Exfoliant',
    brand: 'Lumina Botanicals',
    price: 36,
    rating: 4.86,
    reviewCount: 110,
    stock: 50,
    category: 'exfoliant',
    skinType: ['oily', 'combination'],
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=1000'
    ],
    description: 'Leave-on liquid exfoliant powered by 2% Salicylic Acid (BHA) and Willow Bark to dissolve pore congestion, regulate excess sebum, and prevent acne breakouts.',
    ingredients: ['Water/Aqua', 'Methylpropanediol', 'Salicylic Acid (2%)', 'Camellia Sinensis (Green Tea) Leaf Extract', 'Willow Bark Extract'],
    benefits: ['Dissolves blackheads & clogged pores', 'Controls T-zone oil production', 'Evens out rough skin texture'],
    usage: 'evening',
    volume: '118ml / 4.0 fl. oz.',
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-01-05T00:00:00.000Z',
    updatedAt: '2026-01-05T00:00:00.000Z',
  },
  {
    id: 'lumina-008',
    name: 'French Pink Clay Detoxifying Pore Mask',
    brand: 'Aura Skincare',
    price: 45,
    rating: 4.7,
    reviewCount: 42,
    stock: 28,
    category: 'mask',
    skinType: ['oily', 'combination', 'normal'],
    images: [
      'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=1000'
    ],
    description: 'Purifying mineral pink clay mask enriched with Australian Kaolin, Rose Water, and Niacinamide to refine enlarged pores and extract environmental toxins.',
    ingredients: ['Kaolin Clay', 'Rosa Damascena Flower Water', 'Bentoinite', 'Niacinamide', 'Aloe Vera Leaf Extract', 'Licorice Root Extract'],
    benefits: ['Purifies & tightens visible pores', 'Absorbs excess sebum without drying', 'Leaves skin silky smooth'],
    usage: 'evening',
    volume: '100g / 3.5 oz.',
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    createdAt: '2026-02-12T00:00:00.000Z',
    updatedAt: '2026-02-12T00:00:00.000Z',
  },
  {
    id: 'lumina-009',
    name: 'Multi-Weight Hyaluronic Acid Hydrating Booster',
    brand: 'Lumina Lab',
    price: 68,
    rating: 4.91,
    reviewCount: 175,
    stock: 40,
    category: 'serum',
    skinType: ['all', 'dry', 'sensitive'],
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1608248597262-838d14f70d0a?auto=format&fit=crop&q=80&w=1000'
    ],
    description: 'Triple-molecular-weight Hyaluronic Acid booster serum that locks in multi-depth hydration for plump, bouncy, and smooth skin.',
    ingredients: ['Sodium Hyaluronate High-MW', 'Hydrolyzed Hyaluronic Acid Low-MW', 'Sodium Acetylated Hyaluronate', 'Pro-Vitamin B5', 'Glycerin'],
    benefits: ['Multi-depth cellular hydration', 'Plumps fine dehydration lines', 'Instant watery-light absorption'],
    usage: 'both',
    volume: '30ml / 1.0 fl. oz.',
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-01-08T00:00:00.000Z',
    updatedAt: '2026-01-08T00:00:00.000Z',
  },
  {
    id: 'lumina-010',
    name: 'Niacinamide 10% + Zinc Pore Control Serum',
    brand: 'Lumina Botanicals',
    price: 34,
    rating: 4.82,
    reviewCount: 130,
    stock: 65,
    category: 'serum',
    skinType: ['oily', 'combination', 'sensitive'],
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1608248597262-838d14f70d0a?auto=format&fit=crop&q=80&w=1000'
    ],
    description: 'High-concentration Niacinamide (Vitamin B3) paired with Zinc PCA to balance shine, minimize dark spot discoloration, and calm inflammation.',
    ingredients: ['Water/Aqua', 'Niacinamide (10%)', 'Zinc PCA (1%)', 'Allantoin', 'Tamarindus Indica Seed Polysaccharide'],
    benefits: ['Controls active sebum breakout oiliness', 'Fades post-acne dark marks', 'Calms facial redness'],
    usage: 'both',
    volume: '30ml / 1.0 fl. oz.',
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-01-12T00:00:00.000Z',
    updatedAt: '2026-01-12T00:00:00.000Z',
  },
  {
    id: 'lumina-011',
    name: 'Overnight Rejuvenating Squalane Facial Oil',
    brand: 'Aesop Luxe',
    price: 76,
    rating: 4.89,
    reviewCount: 68,
    stock: 22,
    category: 'moisturizer',
    skinType: ['dry', 'sensitive', 'normal'],
    images: [
      'https://images.unsplash.com/photo-1608248597262-838d14f70d0a?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=1000'
    ],
    description: '100% Plant-Derived Squalane facial oil infused with Marula and Golden Jojoba. Delivers intense nourishment and luminous sheen overnight.',
    ingredients: ['100% Sugarcane-Derived Squalane', 'Sclerocarya Birrea (Marula) Seed Oil', 'Simmondsia Chinensis (Jojoba) Oil', 'Vitamin E'],
    benefits: ['Non-comedogenic weightless oil lock', 'Restores natural skin radiance', 'Soothes stressed environment-exposed skin'],
    usage: 'evening',
    volume: '50ml / 1.7 fl. oz.',
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    createdAt: '2026-02-14T00:00:00.000Z',
    updatedAt: '2026-02-14T00:00:00.000Z',
  },
  {
    id: 'lumina-012',
    name: 'Gentle AHA 7% Glycolic Exfoliating Tonic',
    brand: 'Lumina Lab',
    price: 38,
    rating: 4.79,
    reviewCount: 92,
    stock: 35,
    category: 'exfoliant',
    skinType: ['dry', 'normal', 'combination'],
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=1000'
    ],
    description: 'Targeted AHA liquid toner containing 7% Glycolic Acid and Tasmanian Pepperberry to gently sweep away dead surface cells and restore glass skin clarity.',
    ingredients: ['Water/Aqua', 'Glycolic Acid (7%)', 'Aloe Barbadensis Leaf Water', 'Tasmannia Lanceolata Fruit/Leaf Extract', 'Glycerin'],
    benefits: ['Exfoliates dead skin buildup', 'Improves skin tone luminosity', 'Helps serum absorption'],
    usage: 'evening',
    volume: '240ml / 8.0 fl. oz.',
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false,
    createdAt: '2026-01-18T00:00:00.000Z',
    updatedAt: '2026-01-18T00:00:00.000Z',
  }
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    code: 'GLOW20',
    discountPercent: 20,
    minPurchase: 50,
    expiryDate: '2026-12-31',
    isActive: true,
  },
  {
    code: 'WELCOME10',
    discountAmount: 10,
    minPurchase: 40,
    expiryDate: '2026-12-31',
    isActive: true,
  },
  {
    code: 'FREESHIP',
    discountAmount: 15,
    minPurchase: 0,
    expiryDate: '2026-12-31',
    isActive: true,
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-001',
    productId: 'lumina-002',
    userId: 'user-001',
    userName: 'Sophia L.',
    rating: 5,
    title: 'Transformed my hyperpigmentation!',
    comment: 'I have been using this Vitamin C serum every morning for 3 weeks and my dark sun spots have noticeably faded. Plus it sits beautifully under my sunscreen.',
    verifiedPurchase: true,
    createdAt: '2026-01-25T14:30:00.000Z',
  },
  {
    id: 'rev-002',
    productId: 'lumina-002',
    userId: 'user-002',
    userName: 'Elena Rostova',
    rating: 5,
    title: 'Holy Grail antioxidant serum',
    comment: 'The texture is silky, non-sticky, and stable. My skin literally glows. Worth every penny!',
    verifiedPurchase: true,
    createdAt: '2026-02-02T10:15:00.000Z',
  },
  {
    id: 'rev-003',
    productId: 'lumina-001',
    userId: 'user-003',
    userName: 'Marcus Chen',
    rating: 5,
    title: 'Super gentle for sensitive skin',
    comment: 'Does not strip my skin or leave it tight. The natural rosehip scent is calming and luxurious.',
    verifiedPurchase: true,
    createdAt: '2026-01-28T18:45:00.000Z',
  }
];
